route:
  group_by: [Alertname]
  group_interval: 30s
  repeat_interval: 30s
#Send all the notifications to each of the project participants
  receiver: email-us

receivers:
- name: email-us
  email_configs:
  - send_resolved: true
    to: rollymk20@gmail.com
    from: innopolis_sne22@outlook.com
    smarthost: smtp-mail.outlook.com:587
    auth_username: "innopolis_sne22@outlook.com"
    auth_identity: "innopolis_sne22@outlook.com"
    auth_password: <SMTP_Password>

  - send_resolved: true
    to: Mailtosamsoni@gmail.com
    from: innopolis_sne22@outlook.com
    smarthost: smtp-mail.outlook.com:587
    auth_username: "innopolis_sne22@outlook.com"
    auth_identity: "innopolis_sne22@outlook.com"
    auth_password: <SMTP_Password>

  - send_resolved: true
    to: michaelsopara@gmail.com 
    from: innopolis_sne22@outlook.com
    smarthost: smtp-mail.outlook.com:587
    auth_username: "innopolis_sne22@outlook.com"
    auth_identity: "innopolis_sne22@outlook.com"
    auth_password: <SMTP_Password>
